import type { AetherState } from './types';

export const initialState: AetherState = {
  used: 24391,
  rate: 92000,
  ctxUsed: 78432,
  weekRaw: [46, 40, 44, 38, 50, 42, 62],
  commandsRun: 163,
  activeTab: 'Terminal',
  selected: null,
  selectedProject: null,
  selectedMemory: null,
  selectedRealAgent: null,
  cmdHist: [],
  notifs: [],
  unread: 0,
  notifOpen: false,
  alarmLevel: 'ok',
  apprOpen: false,
  approvals: [
    {
      id: 1,
      agent: 'Code Builder',
      i: 'CB',
      hue: '#7ef0ff',
      action: 'Deploy build #214 to production',
      detail: 'vercel · main → prod · 12 files changed',
      risk: 'HIGH',
    },
    {
      id: 2,
      agent: 'Database Agent',
      i: 'DB',
      hue: '#5fffe0',
      action: 'Run schema migration 0043',
      detail: 'adds index on usage_events · est 40s lock',
      risk: 'MED',
    },
  ],
  apprSeq: 3,
  cfg: {
    opMode: 'EDITS',
    renderer: 'classic',
    pulseMode: 'live',
    theme: 'cyan',
    glow: 70,
    glowFx: true,
    capM: 2.0,
    alarm: 120,
    autoThrottle: true,
    sound: false,
    autoCreateDispatchChannels: false,
  },
  agents: [
    {
      i: 'CB',
      name: 'Code Builder',
      task: 'Refactoring auth middleware',
      pct: 62,
      hue: '#7ef0ff',
      eta: '4m',
      share: 0.22,
      hist: [],
      files: [
        { s: '✓', n: 'routes/auth.js', c: '#3be0a0' },
        { s: '›', n: 'middleware/session.js', c: '#7fd8ef' },
      ],
    },
    {
      i: 'UI',
      name: 'UI Designer',
      task: 'Polishing dashboard cards',
      pct: 41,
      hue: '#8ab6ff',
      eta: '7m',
      share: 0.18,
      hist: [],
      files: [
        { s: '✓', n: 'components/Card.tsx', c: '#3be0a0' },
        { s: '›', n: 'components/Grid.tsx', c: '#7fd8ef' },
      ],
    },
    {
      i: 'DB',
      name: 'Database Agent',
      task: 'Indexing usage_events table',
      pct: 78,
      hue: '#5fffe0',
      eta: '2m',
      share: 0.2,
      hist: [],
      files: [{ s: '✓', n: 'migrations/0043.sql', c: '#3be0a0' }],
    },
    {
      i: 'TR',
      name: 'Test Runner',
      task: 'Running integration suite',
      pct: 55,
      hue: '#7fd8ef',
      eta: '5m',
      share: 0.15,
      hist: [],
      files: [{ s: '›', n: 'tests/auth.spec.ts', c: '#7fd8ef' }],
    },
    {
      i: 'DW',
      name: 'Doc Writer',
      task: 'Drafting API reference',
      pct: 24,
      hue: '#9bd0ff',
      eta: '9m',
      share: 0.13,
      hist: [],
      files: [{ s: '·', n: 'docs/api.md', c: '#4e7c8b' }],
    },
  ],
  idleList: [
    { name: 'Web Scraper', last: '2h ago' },
    { name: 'Doc Helper', last: '1d ago' },
  ],
  sys: [
    { label: 'CPU', val: 23, hist: [18, 25, 20, 30, 24, 22, 26, 23] },
    { label: 'MEM', val: 41, hist: [38, 42, 40, 45, 43, 39, 44, 41] },
    { label: 'NET', val: 18, hist: [12, 22, 16, 28, 14, 20, 17, 18] },
    { label: 'DISK', val: 31, hist: [30, 31, 30, 32, 31, 30, 31, 31] },
  ],
  logs: [],
  projects: [
    { name: 'CLI Companion', status: 'BUILDING', pct: 62, hue: '#7ef0ff', crew: ['Code Builder', 'UI Designer'] },
    { name: 'Mobile Beta', status: 'REVIEW', pct: 88, hue: '#8ab6ff', crew: ['Test Runner'] },
    { name: 'Analytics Pipeline', status: 'QUEUED', pct: 0, hue: '#5fffe0', crew: ['Database Agent'] },
    { name: 'Docs Portal', status: 'SHIPPED', pct: 100, hue: '#7fd8ef', crew: ['Doc Writer'] },
  ],
  memories: [
    {
      id: 1,
      name: 'Auth session-invalidation pattern',
      content: 'Code Builder found a reusable session-invalidation pattern while refactoring auth middleware.',
      source: 'Code Builder',
      ts: '09:14',
      pinned: true,
      strength: 92,
    },
    {
      id: 2,
      name: 'Schema migration 0043 shipped clean',
      content: "Database Agent's index migration on usage_events applied with no downtime.",
      source: 'Database Agent',
      ts: '10:02',
      pinned: false,
      strength: 68,
    },
    {
      id: 3,
      name: 'Dashboard card spacing conventions',
      content: 'UI Designer catalogued the spacing/shadow rules used across dashboard cards for future consistency.',
      source: 'UI Designer',
      ts: '11:20',
      pinned: false,
      strength: 41,
    },
    {
      id: 4,
      name: 'CLI Companion naming brainstorm',
      content: 'Early naming brainstorm for the CLI Companion project before the current name was chosen.',
      source: 'operator',
      ts: '08:47',
      pinned: false,
      strength: 22,
    },
  ],
  memSeq: 5,
  providers: [
    { name: 'Aether Core', connected: true },
    { name: 'OpenAI/Codex', connected: false },
    { name: 'Local Ollama', connected: false },
  ],
  routeDefault: 'Auto',
  operatorName: 'Operator',
  chatActionResults: [],
  realUsage: { weeklyTokens: [0, 0, 0, 0, 0, 0, 0], usedThisMonth: 0, burnRatePerMin: 0, weekOverWeekPct: null, lastScanAt: null },
  realAgents: [],
  recentCompletedDispatches: [],
  dispatchChannels: [],
  dispatchUsage: {},
};
